//----------------------------------------------------------------------------
// Copyright Persistant Studios, SARL.
// https://popcornfx.com/popcornfx-community-license/
//----------------------------------------------------------------------------

#include "Nodes/PopcornFXNode_Attribute.h"

#include "EdGraphSchema_K2.h"
#include "K2Node_MacroInstance.h"

#include "PopcornFXSDK.h"
#include "PopcornFXAttributeFunctions.h"
#include "PopcornFXEmitterComponent.h"

#define LOCTEXT_NAMESPACE "PopcornFXNode_Attribute"

//----------------------------------------------------------------------------

UPopcornFXNode_Attribute::UPopcornFXNode_Attribute(const FObjectInitializer &objectInitializer)
:	Super(objectInitializer)
{
	m_MenuCategory = LOCTEXT("MenuCategory", "PopcornFX|Attributes");

	m_FindByName = "InAttributeName";
	m_FindByIndex = "InAttributeIndex";

	m_CustomParameters.Add(TPair<FName, FName>(TPairInitializer<FName, FName>(m_FindByName, UEdGraphSchema_K2::PC_String)));
	m_CustomParameters.Add(TPair<FName, FName>(TPairInitializer<FName, FName>(m_FindByIndex, UEdGraphSchema_K2::PC_Int)));
	m_CustomParametersTooltip.Add("Attribute Name\nint\n\nName of the attribute");
	m_CustomParametersTooltip.Add("Attribute Index\nint\n\nIndex of the attribute");

	m_PinFieldTypeTooltip = "Attribute Type\nPinFieldType\n\nType of the attribute";
}

//----------------------------------------------------------------------------

FName	UPopcornFXNode_Attribute::GetFindModeName() const
{
	static FName	inFindModeName = "FindMode";
	return inFindModeName;
}

//---------------------------------------------------------------------------

UClass *UPopcornFXNode_Attribute::GetSelfPinClass() const
{
	return UPopcornFXEmitterComponent::StaticClass();
}

//----------------------------------------------------------------------------

void	UPopcornFXNode_Attribute::AllocateDefaultPins()
{
	UK2Node::AllocateDefaultPins();

	// Create the execution pins
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	// Create the input pins, here the "Emitter" pin
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, TEXT(""), GetSelfPinClass(), GetSelfName());

	// Find mode pin
	{
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		UEnum *findModeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFXEditor.EPopcornFXAttributeFindMode"), EFindObjectFlags::ExactClass);
#else
		UEnum *findModeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFXEditor.EPopcornFXAttributeFindMode"), true);
#endif // (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		UEdGraphPin *findModePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, findModeEnum, GetFindModeName());

		findModePin->bNotConnectable = true;
		findModePin->DefaultValue = findModeEnum->GetNameStringByValue(m_FindMode);
		findModePin->AutogeneratedDefaultValue = findModePin->DefaultValue;
	}

	const u32	paramCount = m_CustomParameters.Num();
	for (u32 iParam = 0; iParam < paramCount; ++iParam)
	{
		UEdGraphPin *pin = CreatePin(EGPD_Input, m_CustomParameters[iParam].Value, m_CustomParameters[iParam].Key);

		PK_ASSERT(pin != null);
		if (m_FindMode == EPopcornFXAttributeFindMode::ByName && m_CustomParameters[iParam].Key == m_FindByIndex)
		{
			continue;
		}
		else if (m_FindMode == EPopcornFXAttributeFindMode::ByIndex && m_CustomParameters[iParam].Key == m_FindByName)
		{
			continue;
		}

		if (iParam < (u32)m_CustomParametersTooltip.Num() && !m_CustomParametersTooltip[iParam].IsEmpty())
			pin->PinToolTip = m_CustomParametersTooltip[iParam];

		// Disable inline editing of attribute indices (there's not point)
		if (m_CustomParameters[iParam].Key == m_FindByIndex)
		{
			pin->bDefaultValueIsIgnored = true;
		}
	}
	if (m_FindMode == EPopcornFXAttributeFindMode::ByName)
	{
		BreakAndHidePinByName(m_FindByIndex);
	}
	else if (m_FindMode == EPopcornFXAttributeFindMode::ByIndex)
	{
		BreakAndHidePinByName(m_FindByName);
	}

	// Create the return value pin
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, UEdGraphSchema_K2::PN_ReturnValue);

	// Data type pin
	{
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		UEnum *pinTypeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFX.EPopcornFXPinDataType"), EFindObjectFlags::ExactClass);
#else
		UEnum *pinTypeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFX.EPopcornFXPinDataType"), true);
#endif // (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		UEdGraphPin *pinTypePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, pinTypeEnum, GetPinTypeName());
		PK_ASSERT(pinTypePin != null);

		if (!m_PinFieldTypeTooltip.IsEmpty())
			pinTypePin->PinToolTip = m_PinFieldTypeTooltip;

		pinTypePin->bNotConnectable = true;
		pinTypePin->DefaultValue = pinTypeEnum->GetNameStringByValue(m_DataType);
	}

	const EEdGraphPinDirection	pinDirection = m_ValueDirection.GetValue();
	const uint32				pinCount = RequiredPinNum(m_DataType);
	FEdGraphPinType				pinsType;
	GetGraphPinsType(m_DataType, pinsType);

	if (pinCount <= 1)
	{
		CreatePin(pinDirection, pinsType, m_ValueName);
	}
	else
	{
		CreatePin(pinDirection, pinsType, m_ValueNameX);
		//if (pinCount >= 2)
		CreatePin(pinDirection, pinsType, m_ValueNameY);
		if (pinCount >= 3)
			CreatePin(pinDirection, pinsType, m_ValueNameZ);
		if (pinCount >= 4)
			CreatePin(pinDirection, pinsType, m_ValueNameW);
	}
}

//----------------------------------------------------------------------------

bool		UPopcornFXNode_Attribute::SetupNativeFunctionCall(UK2Node_CallFunction *functionCall)
{
	if (m_FindMode == EPopcornFXAttributeFindMode::ByName)
	{
		return SetupNativeFunctionCallByName(functionCall);
	}
	else
	{
		return SetupNativeFunctionCallByIndex(functionCall);
	}
}

//----------------------------------------------------------------------------

void	UPopcornFXNode_Attribute::PostReconstructNode()
{
	Super::PostReconstructNode();

	if (m_FindMode == EPopcornFXAttributeFindMode::ByName)
	{
		BreakAndHidePinByName(m_FindByIndex);
	}
	else
	{
		BreakAndHidePinByName(m_FindByName);
	}
}

//----------------------------------------------------------------------------

void	UPopcornFXNode_Attribute::PinDefaultValueChanged(UEdGraphPin *pin)
{
	Super::PinDefaultValueChanged(pin);

	if (pin == FindPinChecked(GetFindModeName()))
	{
#if (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		UEnum *pinTypeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFXEditor.EPopcornFXAttributeFindMode"), EFindObjectFlags::ExactClass);
#else
		UEnum *pinTypeEnum = FindObject<UEnum>(null, TEXT("/Script/PopcornFXEditor.EPopcornFXAttributeFindMode"), true);
#endif // (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7)
		check(pinTypeEnum);
		int32		rawValue = pinTypeEnum->GetValueByName(FName(*pin->DefaultValue)); // GetValueByName is fine with or without "EPopcornFXAttributeFindMode::"...
		if (!PK_VERIFY(rawValue != INDEX_NONE))
		{
			rawValue = EPopcornFXAttributeFindMode::ByName;
		}
		EPopcornFXAttributeFindMode::Type	newValue = (EPopcornFXAttributeFindMode::Type)rawValue;

		if (newValue == m_FindMode)
			return; // no need to ReconstructNode()

		m_FindMode = newValue;
		ReconstructNode();
	}

}

//----------------------------------------------------------------------------

void	UPopcornFXNode_Attribute::AutowireNewNode(UEdGraphPin *FromPin)
{
	Super::AutowireNewNode(FromPin);

	if (!FromPin)
	{
		return;
	}

	// Careful, this only works while we have only one int input
	if (FromPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Int)
	{
		m_FindMode = EPopcornFXAttributeFindMode::ByIndex;
		ReconstructNode();
	}
}

//----------------------------------------------------------------------------

#undef LOCTEXT_NAMESPACE
