// AUTO GENERATED FILE
#pragma once
#define POPCORNFX_PLUGIN_VERSION_MAJOR 2
#define POPCORNFX_PLUGIN_VERSION_MINOR 11
#define POPCORNFX_PLUGIN_VERSION_PATCH 2
#define POPCORNFX_PLUGIN_VERSION_TAG ""
